//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trade2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baskets
    {
        public int BasketId { get; set; }
        public string RefAspNetUserId { get; set; }
        public int RefProductId { get; set; }
        public int Stock { get; set; }
        public decimal TotalCost { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Products Products { get; set; }
    }
}
