//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trade2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPens
    {
        public int OrderPenId { get; set; }
        public Nullable<int> RefOrderId { get; set; }
        public Nullable<int> RefProductId { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
